### ISSUE TITLE
System Message Filter Request

### ISSUE THREAD

**Issue by Dedoooo** [NadyaNayme/TidyChat#13]
Heya! please add an option to show "X has invited you to a party" + "You Invite X to a party" + "Party has disbanded" etc to show on system messages filter. Thank you very much for this awesome plugin!

**Comment by NadyaNayme** [comment]
So this is interesting - I think I have these working in Vanilla chat but for some reason in Chat2 I'm not seeing the messages. Going to test more to rule out any possibility that it is a potential bug with Chat2.

![1644731128](https://user-images.githubusercontent.com/4567166/153740594-be50b48b-28a7-484e-ac41-99ce4ae4df39.png)

**Comment by Dedoooo** [comment]
everything works perfectly on my end even with Chat2! i just did some testing and wanted to add to my suggestions to show if "X has left the party." as an option as well 😄 

could it be possible that you didn't add these system messages to the Chat tab you're using and thats why they're not showing for you? some general settings are all over the place so you have to tick them in Chat 2

**Comment by NadyaNayme** [comment]
All of the party messages go through as System messages and both my vanilla and Chat2 settings are set to allow everything for the sake of testing Tidy Chat. I'll consider Tidy Chat to be complete when I only have to filter out channels that I truly never want to see a single message from. I'll chalk it up to something weird going on because I've also had feedback it's working just fine for other people - I don't have friends to easily test this stuff with lol.

I've added a "Show players leaving party" option that will roll out in the next release.
