### ISSUE TITLE
Getting certain messages with that option turned off

### ISSUE THREAD

**Issue by CerbStarraiser** [NadyaNayme/TidyChat#21]
I am getting the following messages though they are turned off in TidyChat.

Other P. obtains X item.
Ren S. obtains X item.  (I'm actually okay with seeing my own obtains item, if that's an option.)
A bonus of X has been awarded for using the duty roulette.
A bonus of X has been awarded for being the adventurer in need.  (Assume both of these are part of duty roulette bonus?)
![image](https://user-images.githubusercontent.com/65967003/154384639-f1b8d0b7-9242-4157-ab4a-c672958a314a.png)

![image](https://user-images.githubusercontent.com/65967003/154384693-b688fd77-2435-422f-97a5-43ec87412c59.png)

That's all for now.  Thank you!

**Comment by NadyaNayme** [comment]
Roulette & bonus bugs identified: You don't get exp if you're at max level so I can't rely on that being awarded in the message text. I'll nuke experience from the text check in the next update which should resolve that problem.

> Ren S. obtains X item. (I'm actually okay with seeing my own obtains item, if that's an option.)

This works with Full Name settings but First L. and F. Last seem to screw around with certain messages by replacing <You> which is how I identify whether or not something is yours. I'm planning on adding player name detection so then I can check against "First Last", "First L.", "F. Last", and "F.L." with initialized ones providing a warning that false positives will happen if anyone shares the same name+initial or initials.

**Comment by NadyaNayme** [comment]
Pushed out an update that is quite possibly the ugliest - but most genius - code that I've written for TidyChat yet. It should fix filters for you - please keep me updated!

When you install the next update please open the settings menu so that Tidy Chat can get your player name.

**Comment by NadyaNayme** [comment]
*sigh*

Gotta push out one more update - it works for same names on the same server but not cross-server parties.

**Comment by NadyaNayme** [comment]
Final update on this. These bugs were from me not looking all too carefully at the actual messages being sent.

[Cast lot] messages for _you_ with initialized name settings results in the message using his/her instead of "your" in the cast lot message. It also uses _plural_ forms.

eg. 

- `Example N. **obtains** a` vs `you **obtain** a`). 
- `Example N. casts his lot for [item].` instead of `You cast **your** lot for [item]`.

I've reworked a good number of filters and relaxed some of the matching (because I don't _need_ to be as precise as I was being for a lot of the matches) and hopefully this irons out most if not all of these bugs.

On my side of things I secretly update your name to "you" before passing the message to the filters. This doesn't change the message that is sent to the chat logs - only the ones I'm checking against the filters. So "Ren S. obtains a" secretly becomes "you obtains a" and I match against that.


**There will be false positives** if anyone has the same name+initial pair (as previously mentioned). But when you open your Tidy Chat settings I capture your character name and filters from then on will replace your name, your initialized name, and your initials with "you" before filtering.

**Comment by fearkite** [comment]
Hey NadyaNayme! Awesome addon btw! :D
I've also found a bug - 'Show volume control messages' doesn't seem to be working, it'll hide it regardless if the option is toggled or not. :(
Thanks heaps for the addon, your work is highly appreciated!

**Comment by NadyaNayme** [comment]
Hi fearkite - thanks for the report! I've just fixed it but the fix won't be live until the next version is released. I didn't review every single line that Jessidhia gave for the localizations and she accidentally mixed up the En/Ja localization for volume controls so the EN was checking JP and JP was checking EN.

**Comment by fearkite** [comment]
Awesome! Thanks heaps :)

**Comment by NadyaNayme** [comment]
Everything should be working as of v0.1.0.7 so I'll be closing this out. 👍
