### ISSUE TITLE
Option to show "hunt mark slain (1/3)" type messages

### ISSUE THREAD

**Issue by SubtleNudge** [NadyaNayme/TidyChat#27]
Just a minor thing. When I'm doing hunts from the hunt board, I like to check the chat for my progress. Without the plugin, it looks like this:

> You gain 2,307 (+118%) experience points.
Hunt mark automated avenger slain! (1/2)
You gain 2,307 (+118%) experience points.
Hunt mark automated avenger slain! (2/2)
You obtain 1,000 gil.
You gain 216,810 experience points.
You obtain 4 sacks of Nuts.

It would be nice if there was an option to have "Hunt mark automated avenger slain! (1/2)" still show up while the rest of the messages (gil, xp, nuts) get filtered out.

**Comment by NadyaNayme** [comment]
I figured it was a matter of time before this got requested - especially since the icon above the mark's head has a small delay. Just didn't want to add it until it got requested (out of laziness mostly).

I'll get it added in the next release.

**Comment by NadyaNayme** [comment]
Added in v0.1.0.9 which is now awaiting PR.

**Comment by NadyaNayme** [comment]
Given those are one-off, non-recurring messages once the logs have been completed and are primarily only messages that beginning players will receive (who I don't really recommend use Tidy Chat as it blocks many otherwise important messages within dungeons that are important to beginners but quite spammy to veterans) I'd recommend using the Custom Whitelist to allow "added to hunting log entry" if you wish to see those messages.

For the vast majority of users whitelisting those wouldn't be beneficial - it would mostly just be option bloat and Tidy Chat's options are already quite bloated.
