### ISSUE TITLE
Filter duplicate messages?

### ISSUE THREAD

**Issue by pigsflew** [NadyaNayme/TidyChat#29]
I'd really like to see emotes, *unless* someone's spamming the same emote over and over. So maybe if the same message has been sent within the last n messages, filter it?

**Comment by NadyaNayme** [comment]
So my biggest problem with this is actually a personal one: I'm not skilled enough to know the best way to implement it. A naïve solution will _probably_ work since string equality is a pretty fast calculation but on super busy servers or with a long chat history it might start introducing performance issues where the game locks up/stutters anytime someone sends a message as Tidy Chat tries to determine if it is a recent and duplicate message or not.

I'll implement it the naïve way but if it has any performance issues I'll have to research the topic on how to do this in a performant way. Research on this topic in particular is a bit challenging since every Stackoverflow discussion assumes you're in a position to just block the spammer or prevent them from sending the message at all as an Admin/GM.

**Comment by pigsflew** [comment]
Would it be possible to only look at the last 10 messages or so? i think that would be fairly fast and fixed time

**Comment by NadyaNayme** [comment]
I don't see why not let users configure it themselves - with a sensible default and a warning that higher numbers could possibly impact performance. Seems to be working just fine at 50 or so messages. Testing beyond that gets a bit time consuming.

![1645739722](https://user-images.githubusercontent.com/4567166/155614174-ee5605d3-68c0-41d0-bd2a-ae540090b397.png)

**Comment by NadyaNayme** [comment]
Waiting on PR.

https://github.com/goatcorp/DalamudPlugins/pull/2083
