### ISSUE TITLE
System filter - not filtering glamour or gearset messages

### ISSUE THREAD

**Issue by j3nesis87** [NadyaNayme/TidyChat#33]
System spam filter enabled, 'show message when changing glamour plates' and 'show message when changing gearsets' **unchecked**. System messages "You cast a glamour..." and "DRG (579)" still appear.
![Capture](https://user-images.githubusercontent.com/91991003/157856986-ba7bcee4-1a88-4fb2-bdf5-54644e50ff05.PNG)
.

**Comment by NadyaNayme** [comment]
First report of this I've seen and I haven't pushed a new release in a few days so I'm going to guess that somehow the configuration file wasn't written to properly by Dalamud.

- Is this an ongoing problem or a 1-off issue?
- Did this only happen after updating Tidy Chat or after modifying settings?
- Have you tried toggling the checkboxes on and off to ensure the configuration file is set properly?

Every similar filter issue like this I've come across is from, somehow, Tidy Chat's configuration file getting corrupted causing half of the config file to not read properly resulting in weird behaviors. Since I don't re-use configuration values and only ever add new ones this _shouldn't_ be happening but it's obvious that sometimes it does. Deleting the configuration file has reliably solved any filter issues people are having with Tidy Chat. I know it's annoying to redo all your settings but it really is the only fix I've found.

**Comment by j3nesis87** [comment]
Where is the configuration file? I tried disabling and reinstalling TidyChat from Dalamud but the settings/config persisted, I assume I need to delete the local cfg file.

**Comment by NadyaNayme** [comment]
Glad it resolved the issue. Really wish I could figure out why this happens and if it is something under my control that I can prevent and not an issue with Dalamud itself and outside of my ability to fix.
