### ISSUE TITLE
Setting conflicts with another plugin

### ISSUE THREAD

**Issue by hsramm** [NadyaNayme/TidyChat#36]
"Filter spammy system messages" blocks the "Adventurer in Need" plugin's messages if they are outputted to the "SystemMessage" chat.

**Comment by NadyaNayme** [comment]
I haven't wrote and won't be writing filters for plugin messages because it requires me updating Tidy Chat anytime any other plugin changes the wording of their messages or adds a new type of message or a new plugin gets released that sends messages.

Plugins are encouraged to send to Dalamud's channel which is Debug by default and Tidy Chat does not block any Debug messages. I've yet to see a compelling reason to not let Dalamud plugins use the Debug channel for plugins. If you're trying to control which tab these messages get sent to in-game use a channel like Announcements that's also unfiltered or use Chat2 (when it gets updated for API6) which allows you to set which tabs can see Debug.

If you have a compelling enough reason to not use the Debug channel for these messages you might convince me to write a filter for it.

**Comment by hsramm** [comment]
> I haven't wrote and won't be writing filters for plugin messages because it requires me updating Tidy Chat anytime any other plugin changes the wording of their messages or adds a new type of message or a new plugin gets released that sends messages and I'm not interested in that level of maintenance. In an ideal world Tidy Chat only needs to be updated once per patch - if even that - since not every patch adds new messaging and most/all that does get added is usually more spam.
> 
> Plugins are encouraged to send to Dalamud's channel which is Debug by default and Tidy Chat does not block any Debug messages. I've yet to see a compelling reason to not let Dalamud plugins use the Debug channel for plugins. If you're trying to control which tab these messages get sent to in-game use a channel like Announcements that's also unfiltered or use Chat2 (when it gets updated for API6) which allows you to set which tabs can see Debug.
> 
> If you have a compelling enough reason to not use the Debug channel for these messages you might convince me to write a filter for it.

Good to know. I will swap it to Debug then, thank you for the info!

**Comment by NadyaNayme** [comment]
`PvPTeam` is an unfiltered channel for Tidy Chat - so if you're trying to control which vanilla tab messages get sent to and don't want Tidy Chat to interfere then you can use `PvPTeam` for Dalamud messaging.

Answer brought to you by Shichi who had the same issue and contacted me over Discord.
