### ISSUE TITLE
Hiding some system messages with no toggle

### ISSUE THREAD

**Issue by SnoFox** [NadyaNayme/TidyChat#38]
TidyChat is hiding all output from `/? <command>` as well as the Sightseeing Log's "You have arrived at a vista" messages.

I've attached my config file just in case it's PEBCAK, but I cannot find any settings for that in the system tab.

<details><summary>TidyChat.json</summary>

```
{
  "$type": "TidyChat.Configuration, TidyChat",
  "Version": 0,
  "Enabled": true,
  "EnableDebugMode": false,
  "IncludeChatTag": false,
  "PlayerName": "",
  "Whitelist": [],
  "SentByWhitelistPlayer": true,
  "TargetingWhitelistPlayer": true,
  "ChatHistoryFilter": false,
  "ChatHistoryChannels": 0,
  "ChatHistoryLength": 10,
  "DisableSelfChatHistory": true,
  "NoCoffee": true,
  "FilterSystemMessages": true,
  "FilterEmoteSpam": false,
  "FilterObtainedSpam": true,
  "FilterLootSpam": true,
  "FilterProgressSpam": false,
  "FilterCraftingSpam": false,
  "BetterInstanceMessage": true,
  "UseDTRBar": true,
  "DTRIsEnabled": true,
  "InstanceInDtrBar": true,
  "BetterSayReminder": true,
  "CopyBetterSayReminder": true,
  "BetterCommendationMessage": false,
  "IncludeDutyNameInComms": false,
  "BetterNoviceNetworkMessage": false,
  "HideSRankHunt": false,
  "HideSSRankHunt": false,
  "HideCommendations": false,
  "HideCompletedVenture": false,
  "HideInstanceMessage": false,
  "HideQuestReminder": false,
  "HideUsedEmotes": false,
  "HideOtherCustomEmotes": false,
  "HideReadyChecks": false,
  "HideCountdownTime": false,
  "HideUserLogins": false,
  "HideUserLogouts": false,
  "HideDebugTeleport": true,
  "HideSpideySenses": false,
  "HideAetherCompass": false,
  "HideSearchForItemResults": false,
  "HideExploratoryVoyage": false,
  "HideSubaquaticVoyage": false,
  "ShowGlamoursProjected": false,
  "ShowGearsetEquipped": true,
  "ShowMateriaRetrieved": true,
  "ShowVolumeControlMessage": false,
  "ShowTradeSent": true,
  "ShowTradeCanceled": true,
  "ShowAwaitingTradeConfirmation": false,
  "ShowTradeComplete": true,
  "ShowInviteSent": true,
  "ShowInviteeJoins": true,
  "ShowLeftParty": true,
  "ShowPartyDisband": true,
  "ShowPartyDissolved": true,
  "ShowInvitedBy": true,
  "ShowJoinParty": true,
  "ShowOfferedTeleport": true,
  "ShowSealedOff": true,
  "ShowHuntSlain": true,
  "ShowCompletionTime": true,
  "ShowRelicBookStep": true,
  "ShowRelicBookComplete": true,
  "ShowOnlineStatus": true,
  "ShowAttachToMail": true,
  "ShowObtainedPomander": true,
  "ShowReturnedPomander": true,
  "ShowCairnGlows": true,
  "ShowRestoresLifeToFallen": true,
  "ShowCairnActivates": true,
  "ShowTransference": true,
  "ShowAetherpoolIncrease": true,
  "ShowAetherpoolUnchanged": true,
  "ShowPomanderOfSafety": true,
  "ShowPomanderOfSight": true,
  "ShowPomanderOfAffluence": true,
  "ShowPomanderOfFlight": true,
  "ShowPomanderOfAlteration": true,
  "ShowPomanderOfWitching": true,
  "ShowPomanderOfSerenity": true,
  "ShowFloorNumber": true,
  "ShowSenseAccursedHoard": true,
  "ShowDoNotSenseAccursedHoard": true,
  "ShowDiscoverAccursedHoard": true,
  "ShowObtainedGil": true,
  "ShowObtainedMGP": true,
  "ShowObtainedClusters": true,
  "ShowObtainedWolfMarks": true,
  "ShowObtainedSeals": true,
  "ShowObtainedAlliedSeals": true,
  "ShowObtainedCenturioSeals": true,
  "ShowObtainedNuts": true,
  "ShowObtainedVenture": true,
  "ShowObtainedMaterials": true,
  "ShowObtainedTribalCurrency": true,
  "ShowObtainedShards": true,
  "ShowGainExperience": false,
  "ShowRouletteBonus": false,
  "ShowAdventurerInNeedBonus": false,
  "ShowGainPvpExp": false,
  "ShowEarnAchievement": false,
  "ShowOtherEarnedAchievement": false,
  "ShowObtainedPoeticsTomestones": true,
  "ShowObtainedAphorismTomestones": true,
  "ShowObtainedAstronomyTomestones": true,
  "ShowLootRoll": true,
  "ShowCastLot": false,
  "ShowOthersLootRoll": true,
  "ShowOthersCastLot": false,
  "ShowOthersObtain": false,
  "ShowLevelUps": true,
  "ShowOtherLevelUps": true,
  "ShowAbilityUnlocks": true,
  "ShowAttachedMateria": true,
  "ShowOvermeldFailure": true,
  "ShowMateriaShatters": true,
  "ShowMateriaExtract": true,
  "ShowDesynthesisLevel": false,
  "ShowDesynthesisObtains": false,
  "FilterGatheringSpam": false,
  "ShowAetherialReductionSands": true,
  "ShowLocationAffects": true,
  "HideGatheringYield": true,
  "HideGatherersBoon": true,
  "HideGatheringAttempts": true,
  "ShowCaughtFish": true,
  "ShowMeasuringIlms": true
}
```
</details>

While debugging myself, [this](https://github.com/NadyaNayme/TidyChat/blob/master/TidyChat/ChatFilters/FilterSystemMessages.cs#L82-L83) reads to me like TidyChat blocks *all* incoming messages, only allowing the whitelisted messages. This would be the cause of the issue.

I would suggest a reverse approach - I want all messages shown to me except for the few I'm explicitly blocking; or perhaps a toggle, if this is the originally intended outcome. This also holds true for the exception handling; rather than eating data, I'd like to know the information I'm missing.

**Comment by NadyaNayme** [comment]
There are over 12,000 messages that would need to be individually blocked if the inverse method was used - instead of maybe 150-200 or so that need to be whitelisted. I would recommend using NoSoliciting's Blacklist feature if there are only a few dozen messages you don't care about. 

I'll see if there's enough uniqueness or something easy to check for whitelisting `/?` results. 

The arrived at vista is an oversight. I think I've said I was going to add a filter for it twice now on Discord but since I never filed a Github issue for it I've forgotten to add it for the past 2 releases. I'll be sure the next update includes it.

**Comment by SnoFox** [comment]
Bah, who needs well-maintained documentation when I've got the source!?</s>

Joking aside, thanks for the info - I should've read the wiki a bit more. I've re-enabled my NoSoliciting setup in the meantime. I was hoping to piggy back off the community-maintained regexes :]

I'll keep an eye out for the "inverse all" logic - should I rewrite this issue report to be an investigation of that as a feature request or open a new one?

**Comment by NadyaNayme** [comment]
The issue as-is is fine. I'll get around to it later in the week.

**Comment by NadyaNayme** [comment]
I cannot test the vista arrival/departure messages since I have obtained all vistas - but the filter _should_ work and will be included in the next release.

**Comment by NadyaNayme** [comment]
![image](https://user-images.githubusercontent.com/4567166/165884679-363f1572-f629-4756-9028-e05d12e79678.png)

Inverse mode has been added. It only applies to System Messages and not other channels like Progression or Loot/Obtain. When enabled anything that matches a filter is _hidden_ and otherwise all System messages will be shown. "Hide" filters will _Show_ and "Show" filters will _hide_. It doesn't update the settings UI because to not make a total mess of the code would require a pretty significant refactor and I just don't have the time for a setting few people will (or honestly should) be using.

For blocking certain System messages it is a slight improvement over No Soliciting in that it filters only the System messages channel - but the recommended method of doing this is to just write better/more specific regex and use No Soliciting's blacklist feature.
