### ISSUE TITLE
Suggestion: Show someone else's synthesizes a Crafted Items checkbox in Crafting/Gathering

### ISSUE THREAD

**Issue by SubaruYashiro** [NadyaNayme/TidyChat#41]
title

**Comment by NadyaNayme** [comment]
I knew there was something I forgot to add in the last update.....

I'll look into this. Should be just matching `synthesizes` or similar in the Crafting channel. It'll include your own crafts too though because I'm trying to avoid adding any more performance-heavy regexes for super minority edge cases like wanting to see other people's finished crafts but not your own. Excluding your own crafts would mean I need to backreference the match to see who crafted the item and backreferences come at a cost.

**Comment by NadyaNayme** [comment]
Added and will be included in the next release.
![image](https://user-images.githubusercontent.com/4567166/166179283-310befdd-471d-4b88-ada5-b22bb7a2d6f1.png)

**Comment by SubaruYashiro** [comment]
Pretty sure it's already shows that you synthesize something right now (before your next release), but just didn't show what someone else's synthesize. If it really matters, i can just hide it with nosol for my own. But yeah, thank you, looking forward to that release.
