### ISSUE TITLE
"You try on <link>" message

### ISSUE THREAD

**Issue by kaedys** [NadyaNayme/TidyChat#43]
These messages appear to be blocked with no toggle.  When I enable the experimental inverse mode, they properly show up, and they show up under [Debug] with that toggle turned on (though without the link being active), but I cannot find a toggle to enable these messages directly.  

I often use these messages when comparing multiple items or glam options, or when I see an item in an Examine of another player that I'm interested in tracking down myself.  Also, to my knowledge, those chat links are the only _default_ way to try on the _base_ appearance of a glamoured item (try on -> tries on glamoured version -> right click link in chat and 'try on' again -> tries on original appearance).  Simple Tweaks offers a workaround for that particular hurdle (holding shift when selecting 'try on' tries on the base appearance), but it's still a bit annoying not having these messages to track items I'm looking at.

**Comment by NadyaNayme** [comment]
I'll get this added - this will be enabled to show-by-default since as you mentioned it is an important vanilla-experience message. The disable setting will be found under `System -> Hide Messages Tidy Chat Shows By Default`

Leaving this here for personal reference:
https://xivapi.com/LogMessage/3911?pretty=true

**Comment by NadyaNayme** [comment]
This has been added and will be in included in the next release.
