### ISSUE TITLE
Pat Me's /patme output is hidden

### ISSUE THREAD

**Issue by shaver** [NadyaNayme/TidyChat#51]
I have the "Pat Me" plugin installed (https://github.com/MgAl2O4/PatMeDalamud) and TidyChat blocks the /patme output. I can't figure out what it's matching exactly, but I haven't read through the source.

If I turn on debug I get
```
[13:59][TidyChat] [Debug] [System] Pat counter: 10
```

**Comment by NadyaNayme** [comment]
Change your Dalamud settings to not go to System. This should generally be left to go to Debug - but pretty much any other channel will work outside of System due to how Tidy Chat works. I won't be whitelisting plugin messages (again - because they _should_ be going to Dalamud's special Debug channel generally).
![image](https://user-images.githubusercontent.com/4567166/170842230-5ceea3d4-8bbe-4f57-9724-792f39fc06d1.png)


Otherwise this is an issue with PatMe not using Dalamud's chat channel and should be raised with the maintainer/developer of PatMe.

**Comment by shaver** [comment]
Thank you!

**Comment by shaver** [comment]
Hmm, my General Chat Channel is already set to Debug!

**Comment by NadyaNayme** [comment]
Then Pat Me is ignoring Dalamud's general channel and should be updated.
