### ISSUE TITLE
[FILTER] Job-specific level ups

### ISSUE THREAD

**Issue by QuentinMcCarthy** [NadyaNayme/TidyChat#54]
## Filter Request

Job-specific level up messages from players. I'd like to still see combat job level-ups from other players, but the crafter job level-ups can be rather spammy.

In essence; seeing 'attains level 15 arcanist' is OK, but 'attains level 15 weaver' is not.

**Comment by NadyaNayme** [comment]
This is a little too specific - as it means having like 18 variations of the same Regex - but it's possible to setup by blocking other's level up messages and abusing the Whitelist feature by checking `Progress` and in the `First Name` field putting any job names you care to see level ups for. That way you block all level up messages by default but whitelist any for specific jobs/classes.

eg.
![image](https://user-images.githubusercontent.com/4567166/173520256-f68fddfc-df8d-44ad-9a03-16034b2a19a0.png)

You'd need a separate filter for each class/job. Set it up once and you have what you want.

**Comment by QuentinMcCarthy** [comment]
Ok, I'll look into that :)

That begs the question, is there any possibility for custom filters? You have a whitelist, what say a blacklist separate to the pre-existing filters?

**Comment by NadyaNayme** [comment]
I've considered it several times now that filter options have grown to cover most general cases. I've held off on adding a way to blacklist because I'd rather users be able to toggle a checkbox than have to write their own filters - otherwise we're back with the No Soliciting Blacklist issue where everyone is writing their own filters instead of being able to share them. Which is more or less why Tidy Chat was created - slightly more powerful (being able to be scoped to a single chat channel) and pre-written NoSol filters for people. If people could just block things themselves they'd be less likely to request a filter that could benefit everyone using Tidy Chat.

I am planning an overhaul of the whitelist, mostly just the visuals in the config, may turn it into a generic Custom Filters system while I do so. I feel Tidy Chat has covered nearly all general filters and most new requests are getting extremely specific with very personalized setups that might only be used by the single person making the request. So giving users a little more power and possibly updating the Whitelist to also allow for Regex filtering would empower users to do the rest.

**Comment by QuentinMcCarthy** [comment]
Fair enough. Thanks :)

**Comment by NadyaNayme** [comment]
Did the whitelist workaround work for you btw?

I'm hoping to get the block/allow adjustment in the next release at the end of the month - but haven't had much time to work on development and I need to make sure I don't screw up people's configs so it might spend some time in Testing before going to main repo. So it _may_ taker longer. But do know that it is now a planned feature to add.

**Comment by QuentinMcCarthy** [comment]
I ended up not doing the whitelist thing and just disabled "other level ups" entirely because it was too much of a hassle to get it all set up.
