### ISSUE TITLE
POTD & HoH Pomander return messages not shown

### ISSUE THREAD

**Issue by InTheBeef** [NadyaNayme/TidyChat#62]
When TidyChat is enabled & "Show when you return a pomander to the coffer" is enabled the message will still not display. Only the toast notification. Might be the same for obtaining pomanders too. Other messages show fine.

**Comment by NadyaNayme** [comment]
Gunna be honest and say the POTD/HoH stuff was only very lightly tested. There are some good odds that that regex isn't 100% written correctly - but I'm not sure when I'll get around to being able to test/fix it.

_Probably_ sometime after Nov 26th.

**Comment by Noshei** [comment]
changing the english regex line from:
Eng = new Regex(@"^you return the (.*) to the coffer\.$", regexOptions),
to
Eng = new Regex(@"You return the", regexOptions),

should get it to work.  Thats what I used for a custom filter and it worked.  I couldn't test other languages.

**Comment by NadyaNayme** [comment]
That might be too broad as it will catch all "You return the" lines even outside of POTD/HoH (not sure if any exist - would have to check first) but I think I spotted the issue anyway. 

Hopefully can get this updated later this month.

**Comment by thakyZ** [comment]
I went to see if what was up because I could've sworn it had worked in the past. I figured out what it is.
The regex goes something like `^you return the (.*) to the coffer\.$` which is fine and all, but the "coffer." isn't the end of the string.
If you look at the XIV API string examples: https://xivapi.com/LogMessage/7222?pretty=true
There is also the part that says: `You cannot carry any more of that item.`

**Comment by NadyaNayme** [comment]
Thanks for doing a bit of digging - me trying to over optimized is what broke it. :) 

I'll remove the `\.$` at the end of that regex which should allow it to work again. I'll try and get this done later today or sometime tomorrow.

**Comment by NadyaNayme** [comment]
> I'll try and get this done later today or sometime tomorrow.

Boy that was a bad time estimate.

This has been done but some other updates are going to be worked on/pushed through with the next update to Tidy Chat. So hopefully you'll see this soon!

**Comment by NadyaNayme** [comment]
This _should_ be updated in the upcoming release. Just making the necessary changes to update TidyChat for Dalamud API8/Patch 6.3 now.

After release if this is still bugged please let me know! I'm not testing this because I'm done with POTD/HOH myself. :) But I'm fairly certain the issue was the `\.$` I had added trying to micro-optimize the filter.
