### ISSUE TITLE
[FILTER] Linkshell membership messages

### ISSUE THREAD

**Issue by alercah** [NadyaNayme/TidyChat#63]
## Filter Request

**What is the exact in-game message? A screenshot is fine but copy/paste is preferred.**

Player Name invites you to join “Parade of Homes.”
Player Name has joined “Parade of Homes.”
You join “Parade of Homes.”
You leave “Parade of Homes.”

and probably one for another person leaving but I don't know it.

**When does this message happen?**

When a player joins a (CW)LS.

**Why is it important to see this message?**

There's otherwise no way to notice that someone else joined or left. For invites, you might miss the popup text.

**Comment by NadyaNayme** [comment]
So I'm going to leave this open because I think I'm going to have to do this the "proper" way - but I'm also lazy. I've tried the lazy way which _should_ hopefully work without too many false positives.

The false positives is why I'm leaving this open - as the reigns may be too loose now.

Should be included in v1.2.3 once I push it out

**Comment by NadyaNayme** [comment]
I don't even remember what I'm supposed to be checking for but seeing as nobody has been complaining I think whatever I did back in Jan 2023 worked.
