### ISSUE TITLE
/consider /hmm by player is getting filtered

### ISSUE THREAD

**Issue by MadScientist51** [NadyaNayme/TidyChat#64]
In Tidy Chat, the setting `Filter emote spam` is supposed to ignore emote text if the player themselves does it. \/consider & \/hmm emote gets filtered by me when that setting is checked and becomes visible once more when unchecked. While checked, other emotes performed by myself are doing the correct behavior by not being filtered.

I am running version 1.2.2.

**Comment by NadyaNayme** [comment]
Do you happen to have the chat lines for when those emotes are used? The emote filtering is one of the simplest filters in Tidy Chat so I think it's a false negative. I determine if you used an emote by if it includes "you/your" in the text as most emotes start with you/your in the flavor text. So if /consider and /hmm don't include "you" in the flavor text then that's why they are being filtered. 

This is mostly a note for myself - but I'd like if Debug Mode could share which rule was matched when a line is filtered. Would make it even easier to debug things and for people to make reports.

**Comment by MadScientist51** [comment]
![image](https://user-images.githubusercontent.com/89101494/212147060-98507c9d-7460-468a-83fb-7ad27e1109f8.png)

Both /hmm & /consider are for the same emote so they spit out the same line. The first line is what happens when I use it on no one. The second is when I target someone (in this case an NPC)

**Comment by NadyaNayme** [comment]
Thank you! A bit annoying that I'll have to write two filters for these but I can get them added.

**Comment by NadyaNayme** [comment]
This should be included in the next update once I push it out.

**Comment by MadScientist51** [comment]
Unfortunately it looks like in the 1.2.3 update the /consider emote is still getting filtered. Additionally *all* emotes are getting filtered. I've tried /slap, /smile, /dance, /nod, etc. Perhaps trying to fix this particular issue might have broken something elsewhere

**Comment by NadyaNayme** [comment]
Hm... I'll take a another look but I had tested it with `/hmm` in-game when I was working on it and it was the only thing adjusted under the Emotes filters.

I have an idea of what it might've been. I should have some time tonight to look at it.

**Comment by MadScientist51** [comment]
https://user-images.githubusercontent.com/89101494/213970281-58e81a93-d53d-4587-b339-33310416a1b7.mp4

**Comment by MadScientist51** [comment]
Just to see if I'm perhaps doing something wrong here

**Comment by kynetical** [comment]
Disregard, I grabbed 1.2.4 and its working fine now
