### ISSUE TITLE
[FILTER] Retainer Ventures

### ISSUE THREAD

**Issue by xinwen49** [NadyaNayme/TidyChat#65]
## Filter Request

**What is the exact in-game message? A screenshot is fine but copy/paste is preferred.**

**When does this message happen?**
Please add filter for messages when retainers return from ventures

**Why is it important to see this message?**
it helps to maximize effectiveness of ventures without checking for timers every now and then

**Comment by NadyaNayme** [comment]
Retainer ventures shouldn't be getting filtered at all. Make sure you aren't accidentally blocking them using a custom filter.

**Comment by xinwen49** [comment]
I just doublechecked and here are the results
"Hide Completed Venture" option is unchecked, and there are no custom filters at all

**Comment by NadyaNayme** [comment]
Can you let me know what you are sending out your retainers for? Quick ventures or a specific material? I'm thinking maybe there is a false positive for a specific material.

**Comment by xinwen49** [comment]
Currently I send them to quick ventures and I'm in the game when they return

**Comment by NadyaNayme** [comment]
Thanks. I'll send mine out for some ventures and see if I can replicate the issue.

**Comment by NadyaNayme** [comment]
I wasn't able to replicate this - and neither have some other people I've asked to help test for me. 

Do you have `Inverse Mode` toggled on by any chance? If so all the Hide/Show filters are inversed and you may need to _check_ "Hide completed venture" in order to show the messages.

Can you try enabling `Debug Mode` in the Advanced settings and let me know if you receive a Debug message from Tidy Chat when a venture returns? This will basically disabled Tidy Chat - but you only need to enable Debug Mode right before you expect your venture to return if you want to minimize spam. If you don't receive a debug message - something else is blocking the message that isn't Tidy Chat. 

To track this down I'll need to update Debug Mode to tell me which Regex match causes a message to be blocked but that's going to require a large refactor and won't be happening anytime soon.

For the time being you can also try creating a custom filter for `has completed a venture!` and check the System channel and set it to `Allow` - but please do this either after testing the Debug message or if you don't care to test the Debug message and just want a workaround, since this only seems to be affecting you. :)

![image](https://user-images.githubusercontent.com/4567166/215365440-233169e7-02b3-44d9-8281-93f536fba2ce.png)

**Comment by xinwen49** [comment]
![image](https://user-images.githubusercontent.com/123839774/215614039-10531054-c665-4a8d-8ab8-1299b5dea10d.png)
Nope. There are still no messages even in the debug mode. On the screenshot I sent all 4 retainers at almost the same time
I will try the custom filter and tell you if it helps

**Comment by NadyaNayme** [comment]
Thank you. Without a [TidyChat] [Debug] message being sent this means that Tidy Chat is not filtering the message. Debug mode works by relaying any filtered message into the chat - if it doesn't relay the message that means Tidy Chat never saw 
or filtered the message. 

Either the message was never received at all (blocked via game/chat settings) or the message was blocked by another plugin (eg. NoSoliciting or a 3rd party plugin). The custom filter likely won't help in this case.

Retainer messages are sent via the System channel so in your Chat tab settings make sure System messages are set to display.

**Comment by xinwen49** [comment]
Yes, I've just checked my general chat settings and found out that system messages were turned off.
Sorry for the inconvenience.
