### ISSUE TITLE
[BUG] ? [FILTER] <Ready Check messages option>

### ISSUE THREAD

**Issue by FrUct1s** [NadyaNayme/TidyChat#66]
[BUG] ?
"Hide /readycheck message" option (off) still hides "XY has initiated a ready check."

## Filter Request

**What is the exact in-game message? A screenshot is fine but copy/paste is preferred.**
![image](https://user-images.githubusercontent.com/58904408/220970657-328c74b3-45e2-43b1-aad1-abc14f329ce4.png)
![image](https://user-images.githubusercontent.com/58904408/220970745-184deed2-c027-4e18-94f3-76d37b35dde5.png)

**When does this message happen?**
Someone starts a Ready Check

**Why is it important to see this message?**
Trigger off of it so you don't miss Ready Checks

**Comment by NadyaNayme** [comment]
One of the design goals of Tidy Chat early on was to remove any messages that were accompanied by a _much more visible_ action. When a `/readycheck` occurs a giant GUI popup occurs asking you if you are ready - making the chat message entirely redundant. However the `complete` is accompanied by the GUI element _disappearing_ which may not be more immediately obvious.

I don't really see any harm in having that unchecked to also show the other `/readycheck` relevant message though - so I'll get this changed.

I'll get around to removing the `complete` check of the `ready,check,complete` check so that `initiated a ready check` won't get filtered. For the time being you can use the custom whitelist for System messages to whitelist `ready check` if you'd like to see them sooner than the next update.

**Comment by NadyaNayme** [comment]
Better late than never. The Rule has been added for Tidy Chat 2.0

![image](https://github.com/user-attachments/assets/0bf036ef-43a4-4984-9540-6874013401ee)
