### ISSUE TITLE
[FILTER] Party Finder Info (Added in 6.4)

### ISSUE THREAD

**Issue by AcidAshe** [NadyaNayme/TidyChat#70]
Could we have a toggle for the Party Finder info being copied into the chat, a feature that was added in 6.4?

![image](https://github.com/NadyaNayme/TidyChat/assets/33726059/e65b0ff0-87d7-452c-aefd-918e9a22707e)

**When does this message happen?**

Happens when you join Party Finder parties.

**Why is it important to see this message?**

To be able to see what info and strats that the party intended to use when you join. If you are the last to join you can't see them anymore as the party is unlisted immediately. SimpleTweaks had their version of this feature, but since it is now in base game as of 6.4, they have removed it. TidyChat seems to hide these messages by default currently.

**Comment by bayta-88** [comment]
Hello. I am also having this issue. I was wondering if anybody had found a way to configure the plugin to get these messages to appear since they are really useful when joining a party in PF. Thanks in advance.

**Comment by NadyaNayme** [comment]
Nearly a year later and I'm finally getting around to things... sorry! Life's been a lot.

Tidy Chat has a way to prevent filtering for a second for slash commands - I can see if I can hook that function up to fire if `You join <...> party for` gets matched so that the following System messages leak through. I'll try and get it included in the 2.0 rewrite that I am currently working on.

Although I'd argue you should probably be reading this information _before_ joining the party rather than blindly/randomly joining parties. I'd rather people who join blindly be able to see this information though so will cross my fingers that the same way I whitelist slash commands works for party information.

**Comment by bayta-88** [comment]
I think that since I wrote this issue the problem has for some reason corrected itself and now I do get the PF description when I enter an instance. Not sure if I changed some setting or if the way in-game messages or Dalamud works was changed or what. But please do check to make sure :P.
I agree about it being good for people to read the PF description before joining and I do. But sometimes on a long day when you are joining the 10th group trying to get an ultimate kill if you have been in the PF for multiple hours until it finally fills you can forget what the PF description said :P (wait was this UCOB group quickmarch uptime or downtime again...?). So having it appear when you enter the instance can be really helpful :P.
Thanks a lot for your hard work! It really makes the game much more enjoyable to have the chat so clean and configurable.

**Comment by NadyaNayme** [comment]
A setting for this has been added in Tidy Chat 2.0.5 - currently in Testing.

It requires "Show Players Joining Party" enabled since that message is is used to disable the filters for 1 second to allow the Objective/Comments lines to be logged to chat.

![image](https://github.com/user-attachments/assets/3e6980bb-76e6-477c-b9d6-2b4ccfbe9859)
