### ISSUE TITLE
Tidy chat no loger filtering messages

### ISSUE THREAD

**Issue by Riiskyy** [NadyaNayme/TidyChat#72]
Tidychat seems not not be filtering messages properly,, the 2 places i have noticed this is on glam changes and commendations e.g.:

![image](https://github.com/NadyaNayme/TidyChat/assets/30751766/f480dda8-7a00-465a-bf15-8618b9df6746)

![image](https://github.com/NadyaNayme/TidyChat/assets/30751766/06f40a43-519d-4745-a1e5-350b8cc855f2)

![image](https://github.com/NadyaNayme/TidyChat/assets/30751766/1edbbb50-c602-4fbc-9cc6-8136c3024df7)

**Comment by Riiskyy** [comment]
i tried removing the plugin, deleting the config files and deleting the files from installed plugins. after re-installing and reconfiguring it was working but today its back to the same behaviour

**Comment by NadyaNayme** [comment]
You're the only report I've had of this - it could be a conflict with another plugin is causing TidyChat to fail to load or fail to handle messages last. 

Without nuking your config and everything - does removing and re-adding TidyChat fix it for that session (the client being open) and then it breaks again when you next launch the client? 

I'll try to investigate as it could be related to the most recent patch - since TC hasn't seen an update for several patches now as there hasn't been any reason to update it. But if I can't reproduce the issue then I unfortunately also can't fix the issue.

**Comment by Riiskyy** [comment]
Ok yeah to I tested disabling, uninstalling the plugin and then re-installing the plugin. After doing so the 'you cast a glamour...' messages stopped appearing and then after closing and restarting the game when changing jobs linked to different glamour plates the messages started showing in the chat window again.

After logging back in you can see the messages and then see the messages after i enabled/disabled the plugin
![image](https://github.com/NadyaNayme/TidyChat/assets/30751766/79257437-93ca-4f7b-8510-2162e7c55832)


I do get the message when logging in from dalamud that tidychat was loaded 



[16:58]Dalamud vD7.9.0.0 loaded. 76 plugin(s) loaded.
[16:58]    》 Artisan v2.0.0.2 loaded.
[16:58]    》 Auto Jail Marker v3.2.3.0 loaded.
[16:58]    》 AutoRetainer v3.1.3.0 loaded.
[16:58]    》 Better Shadows v1.1.5.0 loaded.
[16:58]    》 Better Targeting System v0.0.7.0 loaded.
[16:58]    》 Blue Mage Helper v3.0.0.0 loaded.
[16:58]    》 Brio v0.1.8.7 loaded.
[16:58]    》 Browsingway v1.5.4.0 loaded.
[16:58]    》 Burning Down the House v1.5.9 loaded.
[16:58]    》 Cammy v2.1.0.7 loaded.
[16:58]    》 Character Data Sync v2.0.0.8 loaded.
....
[16:58]    》 Teleporter v2.0.2.1 loaded.
[16:58]    》 The Great Separator v1.2.6.0 loaded.
[16:58]    》 Tidy Chat v1.2.4.0 loaded.
[16:58]    》 Tourist v1.2.12 loaded.
[16:58]    》 VFXEditor v1.7.7.3 loaded.

not sure why it might be failing to load properly on startup but you are right in that it does appear to be that its at least partially not loading at startup as I'm still able to load up the config window. I tried checking the dalamud log file in debug log level and couldn't see any issues for tidychat except it loading

**Comment by NadyaNayme** [comment]
Tidy Chat is supposed to load with priority - which to my understanding means it is meant to load sooner than other plugins. It's possible something is causing it to not initialize properly or is interfering with it in some way. Unfortunately since you have some 3rd party plugins I can't assume that they aren't causing issues in some way - as all too often the issue is being caused by a 3rd party plugin initializing something it shouldn't or otherwise interfering with 1st party plugins. Given that you're the only person to have reported this issue - you might be the only person using a specific 3rd party plugin alongside Tidy Chat and that might be the source of the issue.

This is going to be a bit tedious since you have 76 plugins - so apologies in advance. Can you do two more tests for me to help me troubleshoot this? I'm not able to replicate it otherwise.

1) Disable all other plugins (shouldn't need to uninstall them) and see if the issue occurs with _only_ Tidy Chat loading. If the issue goes away then the issue isn't with Tidy Chat but another plugin interfering with it. If the issue happens - I can at least be certain the issue is 100% with Tidy Chat and not another plugin and maybe try and find some way to check that Tidy Chat is functioning properly on load and "rehook" into Dalamud's ChatGUI.

2) If the issue doesn't happen - re-enable all non-3rd party plugins you have and see if the issue still occurs.

3) If the issue still doesn't happen - enable ½ of your remaining 3rd party plugins. Keep track of which plugins you're enabling.

4) Continue step 3 by enabling ½ of any remaining plugins until the issue comes back.

5) Determine which of the plugins from one of the recurring Step 4's causes the issue.

**Comment by NadyaNayme** [comment]
Thanks for doing the leg work on that.

I'm not familiar with that specific plugin (as I haven't been very active in Dalamud for quite some time) but it does provide me a place to investigate and see what is potentially conflicting! It's _possible_ the issue is that the plugins are not compatible for some reason or that the issue is actually with Chat Emote Color and not with Tidy Chat. But now that I have a place to look and a way to replicate the issue (by installing Chat Emote Color myself) I can actually dig into debugging this for you and see if it is something I need to fix or the dev of Chat Emote Color needs to fix.

FWIW, while I will try and dig into this over the weekend you _might_ also have better success getting the dev of Chat Emote Color to investigate on their end. If the conflict is something on their side of things they'd be a lot more familiar with their code and what potentially might be conflicting than I would.

**Comment by NadyaNayme** [comment]
Alright - so that specific plugin is in Testing and was added 6 months ago by a dev I'm not familiar with and am not sure if they're still active. So working with them might be difficult...

Looking through the plugin's code nothing jumps out to me as an obvious issue. What I _think_ is happening is CEC is capturing all messages and passing them back as handled through ChatGUI. Because they're coming through ChatGUI and not the FFXIV/Client side of things I think Tidy Chat is ignoring them. Because their plugin isn't being specific in the messages it is handling (it handles all messages rather than only messages relevant to what it does) it's causing Tidy Chat to not see any messages at all. 

I'm not sure there is anything I can even do to fix this issue. My advice would be to reach out to the developer of CEC or stop use of that plugin if you want the functionality of Tidy Chat more.

**Comment by Riiskyy** [comment]
Thanks for looking into that, yeah I did suspect that they weren't active any more when I went and checked the GitHub after locating the problem plugin. Honestly I'm not that bothered about having it, I've kept it disabled since finding it as tidy chat is infinitely more important to me. 

Thanks for taking the time to look in to this and sorry for bothering you. I'll close this issue now

**Comment by NadyaNayme** [comment]
Not a bother at all! While I'm not actively playing FFXIV or pushing out updates for filters (anyone who genuinely wants something allowed/blocked can always use the custom filters built into the plugin until it gets added "officially") I do still care whether or not Tidy Chat works! So I appreciate the report and it's good to know for the future in case I come across anyone else trying to use Chat Emote Color as I can let them know they'll need to disable it for Tidy Chat to work. 

Honestly you did a lot more to solve this issue than I did - with all the legwork of testing your plugins. I should be the one thanking you. :P 

Very glad the mystery has been solved.
