### ISSUE TITLE
6.5 AoE (friendly or hostile) causes stutters

### ISSUE THREAD

**Issue by TheFwuffernaut** [NadyaNayme/TidyChat#75]
o7 apologies for the bother but with 6.5 I and a few friends have started having stuttering issues during aoe GCDs/oGCDs/enemy attacks and after some testing we've narrowed it down to TidyChat (as far as we can tell).
We aren't really sure what's causing it on a more in-depth level, is there anything we can provide to help find the issue if its not immediately apparent?
It is definitely tidy chat though - we went through and disabled every other plugin then tested 1 by 1 (e.g. no Penumbra running at the same time)

**Comment by NadyaNayme** [comment]
If you're willing to do some additional testing for me - can you try enabling/disabling specific channel filters? Like disable "Filter Loot messages", "Filter system messages", etc? Can you also provide more information on which GCDs/enemy attacks it was stuttering on?

With how Tidy Chat works and with how fast regex is it shouldn't have any impact on performance unless you're somehow getting thousands of game messages a second. So this is an extra bizarre issue.

**Comment by TheFwuffernaut** [comment]
More than happy to test it later today ^^

Player GCD side its most noticeable on large aoe packs in dungeons but significantly less impactful, mob aoe side I've been experiencing the issue with all raidwides and phase 2's baited proteans in DSR/DSU (w/e you want to call it), along w/ p12s and the 6.5 trial - with much fewer issues outside of those but still noticeable drops.
I should note however that the proteans have a noticeable stutter to them even with tidychat disabled - its just much less of a stutter (quarter second compared to 2s freeze); so those may be a bad interaction rather than tidychat.

I'll get exactly what I had enabled and then do 1 by 1 testing of what should be causing things like that to happen o7

When I do said testing is there anything I should record/make sure is logged beyond just what settings I have enabled/disabled?

**Comment by NadyaNayme** [comment]
> When I do said testing is there anything I should record/make sure is logged beyond just what settings I have enabled/disabled?

It'll spam the chat but enabling Debug Mode for a period of time so that Tidy Chat logs everything it is filtering to the chat can help as it will show all messages that Tidy Chat is attempting to filter (any matched filters will pass through with a [Debug] attached). It's possible I'm matching on a chat line with a poorly optimized regex and may need to rewrite the rule. 

Do you have any Custom Filters setup by the way? I don't think anyone would ever have a super complex regex filter setup but a poorly enough written one could also cause stuttering in theory.

**Comment by TheFwuffernaut** [comment]
o7 just did some testing today - no chance to do DSR tests due to PF but I did test in the 6.5 trial.
It's not consistent in when it spikes at all outside of "generally on raidwides" - first and 2nd line stack were the worst later ones were fine for example, set to 0 had no lag today but was an issue previously.
Its definitely still happening but its also nowhere near as bad as it was so I think this isn't tidychat so much as 6.5 fucking something up/a combination of small spikes causing a singular big one from multiple plugins experiencing the same issue (and/or my hardware being problematic in general - nvidia card on new patch and all :))) ).
I attached screenshots of all my usual settings - 0 custom filters and there WAS a noticeable difference between system filter on/off but that was it as far as I could tell from testing.
Also again as I said it wasn't consistent at all and much less bad compared to before so I may just be wrong here about all this.


![image](https://github.com/NadyaNayme/TidyChat/assets/65637601/54c805e1-b7fa-475d-b538-da3cf5cadd42)
![image](https://github.com/NadyaNayme/TidyChat/assets/65637601/cc70197d-d49a-47cd-843d-68f1d71c06d5)
![image](https://github.com/NadyaNayme/TidyChat/assets/65637601/9aa32a12-109f-494b-96ce-65a2c21d1bfd)
![image](https://github.com/NadyaNayme/TidyChat/assets/65637601/5fe2c40d-659a-453a-a9cb-0fae5b2f2d7f)
![image](https://github.com/NadyaNayme/TidyChat/assets/65637601/3f7cb364-f5f3-4e38-b1f5-9af60773ae1c)

**Comment by NadyaNayme** [comment]
During those raidwides does the boss even have any dialogue that gets sent to the chat box? If there's nothing being sent to chat during those times it can't be Tidy Chat since Tidy Chat only performs logic when a chat message is received. 

I can't imagine what it would be - especially if it's a 1s~ hang. Regex won't really run into performance issues. Even a very poorly written regex can run 10,000 - 100,000 times/second with no issue on text that is <1000 characters. The patch not getting along with your GPU/drivers is honestly a more plausible explanation. 

I have some pretty questionable regex patterns in Tidy Chat but even the worst of them can run 1,000,000's of times per second without issue on the average line of text of a chat message.

**Comment by TheFwuffernaut** [comment]
It's probably not tidychat then and probably something 6.5/hardware side that's causing the issue - apologies for the thread regarding all this then ^^''

The boss doesn't have anything for the 2nd/3rd line stacks in chat - there is a popup saying "X drinks deep of Y's soul..." as its casting thoug (and it does line up with Thordan's "WHAT" in DSR for proteans although I don't think that gets sent to chat? Just a voiceline) so afaik its just in the battle log which I have system messages set to come out to as well hence me thinking that something was going wrong there.

**Comment by NadyaNayme** [comment]
No worries about it. System messages showing in battle tab won't change how Tidy Chat handles them as they're still sent via the System channel. "Where" a chat line comes from is different from which chat tabs it gets displayed in.

I still appreciate the report. It still helps because if I get more reports I can see if they're also using Nvidia GPU's and maybe what driver version they're running on. If I get reports from an AMD user along the same lines it might warrant some extra investigation into whats going on - but raidwides w/o chat lines shouldn't be a Tidy Chat-related thing.
