### ISSUE TITLE
Consistent stuttering in trials with the plugin enabled

### ISSUE THREAD

**Issue by RadicalInquisitor** [NadyaNayme/TidyChat#76]
In any trial duty (As long as other players or NPCs are present, IE not solo) having the plugin enabled will cause consistent frame drops/microstutters whenever the boss begins to attack or use large effects. This is easily reproducible by toggling the plugin on and off while fighting in the one available trust trial from Endwalker. It does not occur with the plugin disabled.

I'm on win 10, running the game from an SSD.
GPU: 3070TI
32GB RAM
 AMD Ryzen 9 7900
 
 I would be happy to provide any other info necessary.

**Comment by NadyaNayme** [comment]
Have a look over #75 and DM me your config on Discord if you can (same name as here: NadyaNayme). Do you have problems in similar situations to Fwuffernaut? This is really bizarre behavior for Tidy Chat to cause. For example, there isn't any code in Tidy Chat that cares about other players/NPCs being present or not. So that you are solo or with other players/NPCs shouldn't make any difference whatsoever.

@TheFwuffernaut - Looks like we have our AMD replication of your issue. Though I still haven't the faintest clue as to what would cause this issue.

**Comment by NadyaNayme** [comment]
Can you provide a video with `/xlstats` window visible and provide an `/xllog` after reproducing? This can help narrow down the cause and help prove whether it is 100% Tidy Chat or something else.

**Comment by RadicalInquisitor** [comment]
I'll go ahead and contact you directly for all this via discord, if that's all right. I'm not overly familiar with github, so.

**Comment by TheFwuffernaut** [comment]
hey, just now saw this - I'll queue up for 89 normal with trusts if I can tomorrow and get the /xlstats and /xllog window while reproducing. My hardware is significantly worse in comparison (HDD, GTX 1660, and 16 GB RAM) but I'll try and get what I can ^^

**Comment by NadyaNayme** [comment]
I'm pushing an update that makes it so that blocked message count only happens on territory changes and not during combat if >100 blocked messages are detected. I also changed it so that it should properly count _blocked_ messages and not _all_ messages. 

With the investigation Radical helped me do today we think that might have been the issue.

So please do your testing on v1.2.8 when it is released (hopefully later tonight if not some time tomorrow) that way I can rule out if the blocked message counting was the issue. We don't have much to go off of so I'm hoping that was it. :)

**Comment by TheFwuffernaut** [comment]
just tested it in Barb just now - 0 stutters at all compared to before ^^ I'm not entirely sure where to pull the xllog from (I can see the command open a window but idk if you want me to scroll through that on a recording or something else) - and I recorded the full fight w/ xlstats and task manager open (to show if its a hardware issue for any hangs or freezes) so lmk where you'd like that uploaded if anywhere

**Comment by NadyaNayme** [comment]
No worries. I'm still not sure how the hell the blocked message counter was the issue - but it was. So glad I was able to fix this for you both (and everyone else who was experiencing this but maybe didn't bother to dig into what was causing it). 

Thank you both for being so willing to help and test and whittle down the possibilities of what it could be. I'm not sure I would have discovered the problem had it not been for Radical's willingness to help test.
