### ISSUE TITLE
[FILTER] Wishlist: Ability to show interaction "dialogue" system messages

### ISSUE THREAD

**Issue by natis1** [NadyaNayme/TidyChat#82]
## Filter Request
A lot of quests and objects in the world can be interacted with which leads to system messages rather than standard dialogue. This also sometimes happens in cutscenes. It would be helpful if it were possible to show these system messages while still filtering the rest of the system category. There is no real standard for what can be contained within these messages so it may not be possible to do this unless there is something special identifying these messages. So maybe it would be impossible short of just filtering out everything that isn't one of these messages.

**What is the exact in-game message? A screenshot is fine but copy/paste is preferred.**
An example of what these messages look like
![image](https://github.com/NadyaNayme/TidyChat/assets/2016651/cfbf3193-ed1b-43d8-910a-72d548c62259)

**When does this message happen?**
All over the place.

**Why is it important to see this message?**
I have NPC dialogue printing to a chat window and without the context of these system messages sometimes cutscene meaning can be lost.

**Comment by natis1** [comment]
My current solution is running system in inverse mode and manually blocking all the very common and annoying system messages with custom filters. Ones such as "You cast a glamour." It's a complex workaround albeit one that seems to mostly work.

**Comment by NadyaNayme** [comment]
Yeah this is the same issue as #32 to a large extent. The effort to write filters to catch all these one offs to whitelist them is monumental and I'm not really interested in doing it. I don't really recommend Tidy Chat to be used until after MSQ has been completed - specifically for the reason of potentially blocking important pieces of dialogue just because it happens to come from `System` or perhaps is a false positive of an existing filter.

I personally recommend disabling Tidy Chat entirely during progression - although Inverse Mode should generally work for these purposes as well.
